In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./hardwareStore.csv")

In [18]:
df

,Unnamed: 0,CATEGORY_ID,CATEGORY_NAME,PRODUCT_ID,PRODUCT_NAME,DESCRIPTION,DESCRIPTION - Detail 1,DESCRIPTION - Detail 2,STANDARD_COST,LIST_PRICE,...,REGION_ID,LOCATION_ID,WAREHOUSE_ID,QUANTITY,WAREHOUSE_NAME,ADDRESS,POSTAL_CODE,CITY,STATE,COUNTRY_NAME
0,0,1,CPU,8,Intel Xeon E5-1650 V4,"Speed:3.6GHz,Cores:6,TDP:140W",Speed:3.6GHz,Cores:6,535.47,601.99,...,3,11,8,50,Beijing,40-5-12 Laogianggen,190518,Beijing,Shenzhen,China
1,1,1,CPU,8,Intel Xeon E5-1650 V4,"Speed:3.6GHz,Cores:6,TDP:140W",Speed:3.6GHz,Cores:6,535.47,601.99,...,3,12,9,36,Bombay,1298 Vileparle (E),490231,Bombay,Maharashtra,India
2,2,1,CPU,8,Intel Xeon E5-1650 V4,"Speed:3.6GHz,Cores:6,TDP:140W",Speed:3.6GHz,Cores:6,535.47,601.99,...,2,6,2,97,San Francisco,2011 Interiors Blvd,99236,South San Francisco,California,United States of America
3,3,1,CPU,8,Intel Xeon E5-1650 V4,"Speed:3.6GHz,Cores:6,TDP:140W",Speed:3.6GHz,Cores:6,535.47,601.99,...,2,8,4,67,"Seattle, Washington",2004 Charade Rd,98199,Seattle,Washington,United States of America
4,4,1,CPU,8,Intel Xeon E5-1650 V4,"Speed:3.6GHz,Cores:6,TDP:140W",Speed:3.6GHz,Cores:6,535.47,601.99,...,3,13,6,30,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,1107,5,Storage,273,Western Digital WD101KRYZ,"Series:Gold,Type:7200RPM,Capacity:10TB,Cache:2...",Series:Gold,Type:7200RPM,313.96,443.64,...,2,23,7,170,Mexico City,Mariano Escobedo 9991,11932,Monterrey,Nuevo Le√≥n,Mexico
1108,1108,5,Storage,273,Western Digital WD101KRYZ,"Series:Gold,Type:7200RPM,Capacity:10TB,Cache:2...",Series:Gold,Type:7200RPM,313.96,443.64,...,3,11,8,156,Beijing,40-5-12 Laogianggen,190518,Beijing,Shenzhen,China
1109,1109,5,Storage,273,Western Digital WD101KRYZ,"Series:Gold,Type:7200RPM,Capacity:10TB,Cache:2...",Series:Gold,Type:7200RPM,313.96,443.64,...,2,6,2,264,San Francisco,2011 Interiors Blvd,99236,South San Francisco,California,United States of America
1110,1110,5,Storage,273,Western Digital WD101KRYZ,"Series:Gold,Type:7200RPM,Capacity:10TB,Cache:2...",Series:Gold,Type:7200RPM,313.96,443.64,...,2,9,5,199,Toronto,147 Spadina Ave,M5V 2L7,Toronto,Ontario,Canada
1111,1111,5,Storage,273,Western Digital WD101KRYZ,"Series:Gold,Type:7200RPM,Capacity:10TB,Cache:2...",Series:Gold,Type:7200RPM,313.96,443.64,...,3,13,6,184,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia

In [57]:
X = df[['PRODUCT_ID','STANDARD_COST', 'LIST_PRICE', 'WAREHOUSE_ID']]
y = df['CATEGORY_ID']
X

      PRODUCT_ID  STANDARD_COST  LIST_PRICE  WAREHOUSE_ID
0              8         535.47      601.99             8
1              8         535.47      601.99             9
2              8         535.47      601.99             2
3              8         535.47      601.99             4
4              8         535.47      601.99             6
...          ...            ...         ...           ...
1107         273         313.96      443.64             7
1108         273         313.96      443.64             8
1109         273         313.96      443.64             2
1110         273         313.96      443.64             5
1111         273         313.96      443.64             6

[1112 rows x 4 columns]

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [59]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [60]:
y_pred = knn.predict(X_test)

In [61]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9910313901345291

In [62]:
testdf = df2 = pd.DataFrame(np.array([[273,313.96, 443.64]]), columns=['PRODUCT_ID','STANDARD_COST', 'LIST_PRICE'])
df2

      PRODUCT_ID  STANDARD_COST  LIST_PRICE  WAREHOUSE_ID
1108         273         313.96      443.64             8
1109         273         313.96      443.64             2
1110         273         313.96      443.64             5

In [63]:
pred = knn.predict(df2)

In [68]:
pred[0]

5

In [65]:
distances, indices = knn.kneighbors(X=df2, n_neighbors=5, return_distance=True)
indices[0]

array([373, 481, 609, 787, 417], dtype=int64)

In [66]:
df.iloc[indices[0]]

,Unnamed: 0,CATEGORY_ID,CATEGORY_NAME,PRODUCT_ID,PRODUCT_NAME,DESCRIPTION,DESCRIPTION - Detail 1,DESCRIPTION - Detail 2,STANDARD_COST,LIST_PRICE,...,REGION_ID,LOCATION_ID,WAREHOUSE_ID,QUANTITY,WAREHOUSE_NAME,ADDRESS,POSTAL_CODE,CITY,STATE,COUNTRY_NAME
373,373,2,Video Card,6,Zotac ZT-P10810A-10P,"Chipset:GeForce GTX 1080 Ti,Memory:11GBCore Cl...",Chipset:GeForce GTX 1080 Ti,Memory:11GBCore Clock:1.48GHz,702.35,849.99,...,3,13,6,30,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
481,481,2,Video Card,221,Zotac ZT-P10810C-10P,"Chipset:GeForce GTX 1080 Ti,Memory:11GBCore Cl...",Chipset:GeForce GTX 1080 Ti,Memory:11GBCore Clock:1.65GHz,535.03,759.99,...,3,13,6,185,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
609,609,4,Mother Board,173,ASRock Z270 SuperCarrier,"CPU:LGA1151,Form Factor:ATX,RAM Slots:4,Max RA...",CPU:LGA1151,Form Factor:ATX,264.35,353.98,...,3,13,6,94,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
787,787,5,Storage,128,Kingston,"Speed:DDR4-2133,Type:288-pin DIMM,CAS:15Module...",Speed:DDR4-2133,Type:288-pin DIMM,650.48,741.63,...,3,11,8,27,Beijing,40-5-12 Laogianggen,190518,Beijing,Shenzhen,China
417,417,2,Video Card,3,Corsair CB-9060011-WW,"Chipset:GeForce GTX 1080 Ti,Memory:11GBCore Cl...",Chipset:GeForce GTX 1080 Ti,Memory:11GBCore Clock:1.57GHz,573.51,799.99,...,2,9,5,46,Toronto,147 Spadina Ave,M5V 2L7,Toronto,Ontario,Canada

In [67]:
product = []
distance = []

for i in range(0, len(distances.flatten())):
    if i != 0:
        product.append(df.index[indices.flatten()[i]])
        distance.append(distances.flatten()[i])    

p=pd.Series(product,name='product')
d=pd.Series(distance,name='distance')
recommend = pd.concat([p,d], axis=1)
recommend = recommend.sort_values('distance',ascending=True)

print('Recommendations:')
for i in range(0,recommend.shape[0]):
    print('{0}: {1}, with distance of {2}'.format(i, recommend["product"].iloc[i], recommend["distance"].iloc[i]))

Recommendations:
0: 787, with distance of 0.0
1: 609, with distance of 0.0
2: 481, with distance of 1.0
3: 481, with distance of 2.0
4: 373, with distance of 2.0
5: 609, with distance of 3.0
6: 609, with distance of 3.0
7: 787, with distance of 3.0
8: 481, with distance of 4.0
9: 373, with distance of 5.0
10: 787, with distance of 6.0
11: 417, with distance of 61.230160052052796
12: 112, with distance of 61.230160052052796
13: 338, with distance of 61.230160052052796

In [70]:
df.loc[(df['CATEGORY_ID'] == pred[0]) & (df['WAREHOUSE_ID'] == 6)]

,Unnamed: 0,CATEGORY_ID,CATEGORY_NAME,PRODUCT_ID,PRODUCT_NAME,DESCRIPTION,DESCRIPTION - Detail 1,DESCRIPTION - Detail 2,STANDARD_COST,LIST_PRICE,...,REGION_ID,LOCATION_ID,WAREHOUSE_ID,QUANTITY,WAREHOUSE_NAME,ADDRESS,POSTAL_CODE,CITY,STATE,COUNTRY_NAME
696,696,5,Storage,56,Western Digital WD2500AAJS,"Series:Caviar Blue,Type:7200RPM,Capacity:250GB...",Series:Caviar Blue,Type:7200RPM,15.23,16.99,...,3,13,6,58,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
697,697,5,Storage,57,Western Digital WD20EZRZ,"Series:Blue,Type:5400RPM,Capacity:2TB,Cache:64MB",Series:Blue,Type:5400RPM,58.01,67.34,...,3,13,6,66,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
698,698,5,Storage,95,Western Digital WDS256G1X0C,"Series:Black PCIe,Type:SSD,Capacity:256GB,Cach...",Series:Black PCIe,Type:SSD,85.87,109.99,...,3,13,6,60,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
699,699,5,Storage,96,SanDisk SDSSDHII-480G-G25,"Series:Ultra II,Type:SSD,Capacity:480GB,Cache:N/A",Series:Ultra II,Type:SSD,102.62,141.56,...,3,13,6,60,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
702,702,5,Storage,261,G.Skill TridentZ RGB,"Speed:DDR4-3200,Type:288-pin DIMM,CAS:14Module...",Speed:DDR4-3200,Type:288-pin DIMM,1330.26,1504.99,...,3,13,6,163,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1090,5,Storage,94,Western Digital WD2500AVVS,"Series:AV-GP,Type:5400RPM,Capacity:250GB,Cache...",Series:AV-GP,Type:5400RPM,12.63,15.55,...,3,13,6,71,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
1095,1095,5,Storage,99,Seagate ST1000DX002,"Series:FireCuda,Type:Hybrid,Capacity:1TB,Cache...",Series:FireCuda,Type:Hybrid,55.41,68.06,...,3,13,6,73,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
1100,1100,5,Storage,100,Crucial CT275MX300SSD1,"Series:MX300,Type:SSD,Capacity:275GB,Cache:N/A",Series:MX300,Type:SSD,79.21,97.88,...,3,13,6,74,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
1105,1105,5,Storage,168,Seagate ST31000340NS - FFP,"Series:Barracuda ES,Type:7200RPM,Capacity:1TB,...",Series:Barracuda ES,Type:7200RPM,34.40,43.99,...,3,13,6,80,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia
1111,1111,5,Storage,273,Western Digital WD101KRYZ,"Series:Gold,Type:7200RPM,Capacity:10TB,Cache:2...",Series:Gold,Type:7200RPM,313.96,443.64,...,3,13,6,184,Sydney,12-98 Victoria Street,2901,Sydney,New South Wales,Australia

In [71]:
import pickle
# save the model to disk
filename = 'knn_model.sav'
pickle.dump(knn, open(filename, 'wb'))